# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

r_check_args: '--use-valgrind'

addons:
  apt:
    packages:
      - valgrind

before_install:
  - cat ./valgrindrc >> ~/.valgrindrc

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
