# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

env:
  - PKG_CXXFLAGS='-fsanitize=address -fsanitize=thread -fsanitize=memory -fsanitize=undefined'

compilers:
  - clang

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
